trigger:
  batch: true
  branches:
    include:
    - puff_master

pool: mypool


jobs:
- job:
  container:
    image: sonicdev-microsoft.azurecr.io:443/sonic-slave-bookworm:latest
  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: |
      sudo apt-get update
      sudo apt-get install -y \
        libhiredis-dev \
        libzmq3-dev \
        swig4.0 \
        libdbus-1-dev \
        libteam-dev
      sudo pip3 install lcov_cobertura
    displayName: "Install dependencies"  
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: puffc.sonic-buildimage
      artifact: sonic-buildimage.vs1
      buildVersionToDownload: latest
      allowFailedBuilds: true
      allowPartiallySucceededBuilds: true
      path: $(Build.ArtifactStagingDirectory)/download/swsscommon
      itemPattern: |
        **/libswsscommon_1.0.0_*.deb
        **/libswsscommon-dev_1.0.0_*.deb
        **/libsai*.deb
        **/syncd*.deb
        **/libnl*.deb
        **/libyang*.deb
    displayName: "Download sonic swss common deb packages"
  - script: |
      set -ex
      cd download
      sudo dpkg -i $(find swsscommon/target/debs/bookworm -type f -name '*.deb')
      cd ..
      rm -rf download
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Install libnl3, sonic swss common and sairedis"